### ISSUE TITLE
No search param triggers empty window in Spotify

### ISSUE THREAD

**Issue by tomgenoni** [Nosrac/LBSpotify#1]
Love this plug in. Only issue I'm seeing is if I just want to bring Spotify to the front using this plug-in it seems to do a blank search. The Spotify window goes empty. So if the search is blank maybe just bring the app to the front?

**Comment by Nosrac** [comment]
Hey Tom,

Thanks for the heads up. 

I made a change that I think'll fix your problem.  Would you download again and let me know?

Thanks

**Comment by tomgenoni** [comment]
Yup. Seems to work as expected. Thanks. Didn't the original Spotify launchbar item used to [support searching?](http://computers.tutsplus.com/tutorials/speeding-up-your-life-with-launchbar--mac-57434). At some point it stopped working.

**Comment by Nosrac** [comment]
Hmmm, I'm not sure about that.  This extension adds search support to the default Spotify application launchbar item.

You're saying that's not working for you?

**Comment by tomgenoni** [comment]
Yours works fine. It's just that at some point I thought I was able to do searches. Anyway, everything's working. Thanks for your help.

**Comment by Nosrac** [comment]
Great! Closing this now
