### ISSUE TITLE
Predictions not working

### ISSUE THREAD

**Issue by williamsmj** [Nosrac/LBSpotify#3]
If I hit return then Spotify opens and the search is run, as expected. But until I hit return, I get no predictions in Launchbar. Has the Spotify API changed?

**Comment by lbrt** [comment]
@williamsmj yes, the api has changed. I made a pull request to @Nosrac with the necessary fixes.

**Comment by Nosrac** [comment]
Thanks @lbrt, I've merged your changes.

/cc @williamsmj
